version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9

commands:
  deploy-env:
    description: "Sets up aws cli and ecs-deploy to update a service with a target docker image"
    parameters:
      service-name:
        type: string
      image-name:
        type: string
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - run:
          name: Install jq
          command: |
            sudo apt update
            sudo apt install jq
      - run:
          name: Install ecs deploy
          command: |
              curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
              sudo chmod +x /usr/bin/ecs-deploy
      - run:
          name: Premote target image
          command: |
            ecs-deploy \
            --timeout 104400 \
            --region $AWS_REGION \
            --cluster $CLUSTER_NAME \
            --service-name << parameters.service-name >> \
            --image << parameters.image-name >> \
            --timeout 104400 \
            --use-latest-task-def
          no_output_timeout: 30m

jobs:
  check:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - aws-ecr/ecr-login
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build transactions-api-test
      - run:
          name: Run tests
          command: docker-compose up transactions-api-test

  deploy-to-development:
    docker:
      - image: circleci/python:3.7
    steps:
      - deploy-env:
          service-name: 'transactions-api-development'
          image-name: "$AWS_ECR_HOST/$AWS_ECR_PATH:$CIRCLE_SHA1"

  deploy-to-staging:
    docker:
      - image: circleci/python:3.7
    steps:
      - deploy-env:
          service-name: 'transactions-api-staging'
          image-name: "$AWS_ECR_HOST/$AWS_ECR_PATH:$CIRCLE_SHA1"

  deploy-to-production:
    docker:
      - image: circleci/python:3.7
    steps:
      - deploy-env:
          service-name: 'transactions-api-production'
          image-name: "$AWS_ECR_HOST/$AWS_ECR_PATH:$CIRCLE_SHA1"

workflows:
  build-and-deploy:
      jobs:
      - check
      - aws-ecr/build_and_push_image:
          name: build_and_push_image
          dockerfile: ./transactions-api/Dockerfile
          path: ./transactions-api
          account-url: AWS_ECR_HOST
          repo: $AWS_ECR_PATH
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master

      - deploy-to-development:
          requires:
            - check
            - build_and_push_image
          filters:
            branches:
              only: master

      - permit-staging-release:
          type: approval
          requires:
            - deploy-to-development
          filters:
            branches:
              only: master

      - deploy-to-staging:
          requires:
            - permit-staging-release
          filters:
            branches:
              only: master

      - permit-production-release:
          type: approval
          requires:
            - deploy-to-staging
          filters:
            branches:
              only: master

      - deploy-to-production:
          requires:
            - permit-production-release
          filters:
            branches:
              only: master
